apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
  labels:
    app: products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: spring-boot-app
        image: akshaypatil5596/products:replaceImageTag
        ports:
        - containerPort: 3001